# Mirrors configs/powershell/powershell/aliases.ps1

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias -- '~'='cd ~'
alias -- -='cd -'

if (( $+commands[eza] )); then
  alias l='eza -l --group --color=always --group-directories-first'
  alias ls='eza -al --group --header --icons --group-directories-first'
  alias ll='eza -la --group --icons --group-directories-first'
  alias la='eza -la --group --icons --group-directories-first'
  alias lt='eza --tree --level=2 --icons'
  alias lh='eza -la --group --sort=modified --reverse'
  alias tree='eza --tree --level=4 --icons --long'
else
  alias l='ls -lh --color=auto'
  alias ls='ls -alh --color=auto'
  alias ll='ls -lah --color=auto'
  alias la='ls -lah --color=auto'
  alias lh='ls -lahtr --color=auto'
fi

alias cp='cp -iv'
alias mv='mv -iv'
alias rm='rm -Iv'
alias rf='command rm -rf'
alias mkdir='mkdir -pv'
alias grep='grep --color=auto'

alias df='df -h'
alias du='du -h'
alias free='free -h'
alias top='btop || htop || command top'
alias mem='ps -eo comm,rss --sort=-rss | head -6'
alias cpu='ps -eo comm,%cpu --sort=-%cpu | head -6'

alias ports='ss -tulpn'
alias listening='ss -ltnp'

alias g='git'
alias gs='git status'
alias ga='git add'
alias gaa='git add -A'
alias gc='git commit'
alias gcm='git commit -m'
alias gp='git push'
alias gpu='git push -u origin HEAD'
alias gpl='git pull'
alias gco='git checkout'
alias gb='git branch'
alias gd='git diff'
alias gl='git log --oneline --graph --decorate'
alias gclone='git clone'

alias v='nvim'
alias vv='nvim .'
alias e='micro'
alias n='nano'
alias c='clear'
alias ff='fastfetch'
alias reload='source ~/.zshrc && echo "Reloaded .zshrc"'
alias zshrc='${EDITOR} ~/.zshrc'
alias editrc='${EDITOR} ~/.zshrc'
alias nvimrc='$EDITOR ~/.config/nvim/init.lua'

alias g.='cd ~/.config'
alias conf='cd ~/.config'
alias projects='cd ~/workspace/github && ls'
alias workspace='cd ~/workspace && ls'
alias weather='curl -s "wttr.in?u"'
alias dl='cd ~/Downloads'
alias doc='cd ~/Documents'
alias vid='cd ~/Videos'

alias x='exit'
alias h='history'
alias j='jobs -l'
alias which='type -a'
alias now='date +"%Y-%m-%d %T"'
alias week='date +%V'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias biggest='du -h --max-depth=1 | sort -h'
alias k9='kill -9'
alias killall='killall -v'
alias untar='tar -xvf'
alias ungz='tar -xzvf'
alias unbz2='tar -xjvf'
alias switch='exec bash'

alias -g G='| grep -i'
alias -g L='| less'
alias -g H='| head'
alias -g T='| tail'
alias -g N='2>/dev/null'
alias -g J='| jq'

command -v code-insiders >/dev/null 2>&1 && alias code='code-insiders'
alias treesitter='tree-sitter'
