#!/usr/bin/env bash
conf="${XDG_CONFIG_HOME:-$HOME/.config}/i3/config"
# shellcheck disable=SC2016
filter='s/^[[:space:]]*bindsym[[:space:]]+//; s/--no-startup-id //; s/\$mod/Super/g; s/exec //'
grep -E '^[[:space:]]*bindsym' "$conf" | sed -E "$filter" |
  rofi -dmenu -i -p "Keys" -theme-str 'window {width: 70%;} listview {lines: 18;}' >/dev/null
